# Generated by Django 4.1.7 on 2024-07-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
