# Generated by Django 4.1.7 on 2024-07-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_ventas_mensuale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas_Mensuales2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': ' Admin. Ventas Diarias Tienda 2 ',
            },
        ),
        migrations.AlterModelOptions(
            name='ventas_mensuale',
            options={'verbose_name_plural': ' Admin. Ventas Diarias Tienda 1'},
        ),
    ]
