# Generated by Django 4.1.7 on 2024-07-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_ventas_mensuales2_alter_ventas_mensuale_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventas_Mensuales2',
        ),
    ]
