# Generated by Django 4.1.7 on 2024-07-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_venta2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta2',
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name_plural': ' ADMIN. TICKETS DE VENTA TIENDA 1'},
        ),
        migrations.AlterModelOptions(
            name='ventas_mensuale',
            options={'verbose_name_plural': ' ADMIN . INGRESO TOTAL DIARIO TIENDA 1'},
        ),
    ]
