# Generated by Django 4.1.7 on 2024-08-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0019_conjuntosbossedama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportesGenerales',
            fields=[
                ('fecha', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'ADMIN . REPORTE GENERAL',
            },
        ),
    ]
