# Generated by Django 4.1.7 on 2024-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0032_udjoggerbotapiefraneladama_udjoggerbotapieterrydama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UDpolocroplicradama',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'UD . Polo Crop Licra     ',
            },
        ),
        migrations.CreateModel(
            name='UDpololicramangacortadama',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'UD . Polo Licra Manga Corta     ',
            },
        ),
        migrations.CreateModel(
            name='UDpololicramangalargadama',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'UD . Polo Licra Manga Larga     ',
            },
        ),
    ]
