# Generated by Django 4.1.7 on 2024-08-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0037_udcasacacortavientodama_udcasacalicradama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas_Mensuale2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': ' ADMIN . INGRESO TOTAL DIARIO TIENDA 2',
            },
        ),
    ]
