# Generated by Django 4.1.7 on 2024-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0038_ventas_mensuale2'),
    ]

    operations = [
        migrations.CreateModel(
            name='UDbivididama',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'UD . Bividi      ',
            },
        ),
        migrations.CreateModel(
            name='UDenterizodama',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'UD . Enterizo     ',
            },
        ),
        migrations.CreateModel(
            name='UDtopdama',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'UD . Top     ',
            },
        ),
    ]
