# Generated by Django 4.1.7 on 2024-08-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0039_udbivididama_udenterizodama_udtopdama'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiendaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_excel/')),
                ('tienda1', models.IntegerField()),
                ('tienda2', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'ADMIN . DATOS ESTADÍSTICOS MENSUALES',
            },
        ),
    ]
