# Generated by Django 4.1.7 on 2024-08-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0040_tiendaarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAConjuntoLicraNiña',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CNA . Conjunto Licra Niña     ',
            },
        ),
        migrations.CreateModel(
            name='CNAConjuntoNovaNiña',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CNA . Conjunto Nova Niña     ',
            },
        ),
        migrations.CreateModel(
            name='CNOConjuntoInterfilNiño',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CNO . Conjunto Interfil Niño     ',
            },
        ),
        migrations.CreateModel(
            name='CNOConjuntoNovaNiño',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'CNO . Conjunto Nova Niño     ',
            },
        ),
    ]
