# Generated by Django 4.1.7 on 2024-09-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0042_udpantalonpalazodama'),
    ]

    operations = [
        migrations.CreateModel(
            name='UVpolooversizedama',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'UD . Polos Oversize     ',
            },
        ),
        migrations.CreateModel(
            name='UVpolooversizevaron',
            fields=[
                ('Codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Diseño', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Costo', models.IntegerField(default=18)),
                ('Precio', models.IntegerField()),
                ('S1', models.IntegerField(default=0)),
                ('S2', models.IntegerField(default=0)),
                ('S3', models.IntegerField(default=0)),
                ('Almacen', models.IntegerField(default=0)),
                ('Global', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'UV . Polos Oversize     ',
            },
        ),
    ]
