# Generated by Django 4.1.7 on 2025-04-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0044_unopantalonniño'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventariodeTotales',
            fields=[
                ('fecha', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'ADMIN . REPORTE DE INVENTARIOS TOTAL',
            },
        ),
    ]
